"""PostgreSQL storage for Garmin Coach.

The app's data lives in a local Postgres database (see ``config.DATABASE_URL``).
We use raw ``psycopg`` (v3) with a small connection pool — no ORM — because the
schema is tiny and the app is single-user.

**Deduplication.** Each run is identified by its *start time truncated to the
minute* (``start_minute``, a generated column with a UNIQUE constraint). Inserts
upsert ``ON CONFLICT(start_minute)``, so re-importing the same run — whether it
arrives from a Garmin sync (real activity id) or a CSV export (synthetic id),
and regardless of small differences in the seconds field or rounding — updates
the existing row instead of creating a duplicate.

The ``raw_json`` column keeps the original payload (as JSONB) so we can extract
additional fields later without re-syncing.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta
from typing import Any, Iterable

from psycopg.rows import dict_row
from psycopg.types.json import Jsonb
from psycopg_pool import ConnectionPool

from . import config


SCHEMA = """
CREATE TABLE IF NOT EXISTS activities (
    id                  BIGINT PRIMARY KEY,
    name                TEXT,
    start_local         TEXT NOT NULL,
    -- Start time trimmed to the minute ("YYYY-MM-DD HH:MM"). This is the
    -- natural key we dedup on: the same run always has the same value here.
    start_minute        TEXT GENERATED ALWAYS AS (substr(start_local, 1, 16)) STORED UNIQUE,
    distance_km         DOUBLE PRECISION,
    duration_min        DOUBLE PRECISION,
    avg_pace_min_per_km DOUBLE PRECISION,   -- running: minutes per km
    avg_speed_kmh       DOUBLE PRECISION,   -- cycling: km per hour
    avg_hr              INTEGER,
    max_hr              INTEGER,
    vo2max              DOUBLE PRECISION,
    elevation_gain_m    DOUBLE PRECISION,
    calories            INTEGER,
    activity_type       TEXT,               -- 'running' | 'cycling'
    raw_json            JSONB,
    synced_at           TEXT NOT NULL
);

-- Add avg_speed_kmh to databases created before cycling support existed.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS avg_speed_kmh DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_activities_start_local
    ON activities (start_local);

CREATE INDEX IF NOT EXISTS idx_activities_type
    ON activities (activity_type);

CREATE TABLE IF NOT EXISTS goals (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distance            TEXT NOT NULL,        -- '5k' | '10k' | 'half_marathon' | 'marathon'
    target_date         TEXT,                  -- optional ISO date (YYYY-MM-DD)
    target_time_seconds INTEGER,               -- optional, e.g. 1500 = sub-25:00 5k
    notes               TEXT,
    status              TEXT NOT NULL DEFAULT 'active',  -- 'active' | 'achieved' | 'abandoned'
    created_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role        TEXT NOT NULL,    -- 'user' | 'assistant'
    content     TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weekly_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start  TEXT NOT NULL,
    plan_json   JSONB NOT NULL,
    status      TEXT NOT NULL DEFAULT 'proposed',  -- proposed | accepted | archived
    created_at  TEXT NOT NULL
);

-- Weekly sleep summaries from Garmin's sleep CSV export (1-year view).
-- Kept as the long-term trend backdrop.
CREATE TABLE IF NOT EXISTS sleep_weeks (
    week_start        TEXT PRIMARY KEY,   -- ISO date of the week's first day
    week_label        TEXT,               -- original label, e.g. "Μάι. 18-24"
    avg_score         INTEGER,            -- Garmin sleep score 0–100
    quality           TEXT,               -- Καλό / Άριστη / Αρκετά καλή
    avg_duration_min  DOUBLE PRECISION,   -- average time actually slept
    avg_need_min      DOUBLE PRECISION,   -- average sleep the body needed
    avg_bedtime       TEXT,               -- 24h "HH:MM"
    avg_wake_time     TEXT,               -- 24h "HH:MM"
    synced_at         TEXT NOT NULL
);

-- Per-night sleep detail from Garmin's 1-day sleep CSV export. Captures the
-- stage breakdown (deep/light/REM) and recovery metrics not in the weekly file.
CREATE TABLE IF NOT EXISTS sleep_nights (
    night_date          TEXT PRIMARY KEY,  -- ISO date the sleep ended
    score               INTEGER,
    quality             TEXT,
    duration_min        DOUBLE PRECISION,
    deep_min            DOUBLE PRECISION,
    light_min           DOUBLE PRECISION,
    rem_min             DOUBLE PRECISION,
    awake_min           DOUBLE PRECISION,
    stress_avg          INTEGER,
    restless_moments    INTEGER,
    overnight_hr        INTEGER,           -- avg HR during sleep
    resting_hr          INTEGER,
    body_battery_change INTEGER,
    spo2_avg            INTEGER,
    spo2_low            INTEGER,
    respiration_avg     DOUBLE PRECISION,
    respiration_low     DOUBLE PRECISION,
    hrv_ms              INTEGER,
    hrv_status          TEXT,
    synced_at           TEXT NOT NULL
);

-- Daily calories scraped from Garmin's calories page (7-day table). Keyed on
-- the day, so re-scraping the same date simply overwrites it.
CREATE TABLE IF NOT EXISTS calories (
    day_date     TEXT PRIMARY KEY,   -- ISO date
    activity_cal INTEGER,            -- calories burned by activity/movement
    resting_cal  INTEGER,            -- resting (BMR) calories
    total_cal    INTEGER,            -- activity + resting
    synced_at    TEXT NOT NULL
);

-- The user's personal food library: nutrition per 100 g. The nutrition agent
-- looks foods up here and adds new ones (name stored lowercased for matching).
CREATE TABLE IF NOT EXISTS foods (
    name             TEXT PRIMARY KEY,    -- canonical lowercase name
    kcal_per_100g    DOUBLE PRECISION NOT NULL,
    protein_per_100g DOUBLE PRECISION,
    fat_per_100g     DOUBLE PRECISION,
    carbs_per_100g   DOUBLE PRECISION,
    created_at       TEXT NOT NULL
);

-- One row per thing eaten, with macros computed for that portion. Daily totals
-- are summed from here.
CREATE TABLE IF NOT EXISTS food_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date    TEXT NOT NULL,           -- ISO date eaten
    food_name   TEXT NOT NULL,           -- as logged
    grams       DOUBLE PRECISION,        -- portion eaten
    kcal        DOUBLE PRECISION,
    protein_g   DOUBLE PRECISION,
    fat_g       DOUBLE PRECISION,
    carbs_g     DOUBLE PRECISION,
    created_at  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_food_log_date ON food_log (log_date);
"""

VALID_DISTANCES = ("5k", "10k", "half_marathon", "marathon")
VALID_GOAL_STATUSES = ("active", "achieved", "abandoned")


# --------------------------- Connection pool -------------------------------

_pool: ConnectionPool | None = None


def _get_pool() -> ConnectionPool:
    """Return the process-wide connection pool, creating it on first use.

    A pool keeps a handful of live connections open and hands them out as
    needed — far cheaper than opening a brand-new TCP+auth connection for
    every query (which is what a naive Postgres setup would do).
    """
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            conninfo=config.DATABASE_URL,
            min_size=1,
            max_size=5,
            kwargs={"row_factory": dict_row},
            open=True,
        )
        _ensure_schema(_pool)
    return _pool


def _ensure_schema(pool: ConnectionPool) -> None:
    """Create tables/indexes if they don't exist yet (idempotent)."""
    statements = [s.strip() for s in SCHEMA.split(";") if s.strip()]
    with pool.connection() as conn:
        for stmt in statements:
            conn.execute(stmt)


def get_connection():
    """Borrow a connection from the pool as a context manager.

    Usage::

        with get_connection() as conn:
            conn.execute(...)

    The connection is returned to the pool (and the transaction committed, if
    no exception was raised) when the ``with`` block exits.
    """
    return _get_pool().connection()


# ----------------------------- Activities ----------------------------------


def upsert_activity(
    summary: dict[str, Any],
    raw: dict[str, Any] | None = None,
) -> None:
    """Insert or update one activity row from a ``summarize_activity()`` dict.

    Deduplicated on ``start_minute`` (start time to the minute), so re-importing
    the same run updates the existing row rather than adding a duplicate. When a
    conflict happens we keep the *largest* id (real positive Garmin ids beat
    synthetic negative CSV ids) and use ``COALESCE`` so a sparser later import
    never wipes out data (e.g. VO2max/HR) from a richer earlier one.
    """
    if summary.get("id") is None:
        return  # can't store without a primary key

    payload = {
        "id": summary.get("id"),
        "name": summary.get("name"),
        "start_local": summary.get("start_local"),
        "distance_km": summary.get("distance_km"),
        "duration_min": summary.get("duration_min"),
        "avg_pace_min_per_km": summary.get("avg_pace_min_per_km"),
        "avg_speed_kmh": summary.get("avg_speed_kmh"),
        "avg_hr": summary.get("avg_hr"),
        "max_hr": summary.get("max_hr"),
        "vo2max": summary.get("vo2max"),
        "elevation_gain_m": summary.get("elevation_gain_m"),
        "calories": summary.get("calories"),
        "activity_type": summary.get("activity_type"),
        "raw_json": Jsonb(raw) if raw is not None else None,
        "synced_at": datetime.utcnow().isoformat(),
    }

    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO activities
                (id, name, start_local, distance_km, duration_min,
                 avg_pace_min_per_km, avg_speed_kmh, avg_hr, max_hr, vo2max,
                 elevation_gain_m, calories, activity_type, raw_json, synced_at)
            VALUES
                (%(id)s, %(name)s, %(start_local)s, %(distance_km)s, %(duration_min)s,
                 %(avg_pace_min_per_km)s, %(avg_speed_kmh)s, %(avg_hr)s, %(max_hr)s, %(vo2max)s,
                 %(elevation_gain_m)s, %(calories)s, %(activity_type)s, %(raw_json)s, %(synced_at)s)
            ON CONFLICT (start_minute) DO UPDATE SET
                id                  = GREATEST(activities.id, excluded.id),
                name                = excluded.name,
                start_local         = excluded.start_local,
                distance_km         = COALESCE(excluded.distance_km, activities.distance_km),
                duration_min        = COALESCE(excluded.duration_min, activities.duration_min),
                avg_pace_min_per_km = COALESCE(excluded.avg_pace_min_per_km, activities.avg_pace_min_per_km),
                avg_speed_kmh       = COALESCE(excluded.avg_speed_kmh, activities.avg_speed_kmh),
                avg_hr              = COALESCE(excluded.avg_hr, activities.avg_hr),
                max_hr              = COALESCE(excluded.max_hr, activities.max_hr),
                vo2max              = COALESCE(excluded.vo2max, activities.vo2max),
                elevation_gain_m    = COALESCE(excluded.elevation_gain_m, activities.elevation_gain_m),
                calories            = COALESCE(excluded.calories, activities.calories),
                activity_type       = excluded.activity_type,
                raw_json            = COALESCE(excluded.raw_json, activities.raw_json),
                synced_at           = excluded.synced_at
            """,
            payload,
        )


def upsert_many(items: Iterable[tuple[dict[str, Any], dict[str, Any]]]) -> int:
    """Bulk upsert; each item is ``(summary, raw_dict)``. Returns count inserted/updated."""
    count = 0
    for summary, raw in items:
        upsert_activity(summary, raw)
        count += 1
    return count


def get_recent_activities(days: int = 30, limit: int = 200) -> list[dict[str, Any]]:
    """Return activities from the last ``days`` days, newest first."""
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM activities
            WHERE start_local >= %s
              AND activity_type = 'running'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (cutoff, limit),
        ).fetchall()
    return [dict(r) for r in rows]


def get_recent_cycling(days: int = 30, limit: int = 200) -> list[dict[str, Any]]:
    """Return cycling rides from the last ``days`` days, newest first.

    Used as cross-training context for the running coach.
    """
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, name, distance_km, duration_min,
                   avg_speed_kmh, avg_hr, calories
            FROM activities
            WHERE start_local >= %s
              AND activity_type = 'cycling'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (cutoff, limit),
        ).fetchall()
    return [dict(r) for r in rows]


def get_activity_by_id(activity_id: int) -> dict[str, Any] | None:
    """Return a single activity row by primary key, or None if not found."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM activities WHERE id = %s",
            (activity_id,),
        ).fetchone()
    return dict(row) if row else None


def count_activities() -> int:
    """Total number of stored activities."""
    with get_connection() as conn:
        row = conn.execute("SELECT COUNT(*) AS n FROM activities").fetchone()
    return int(row["n"]) if row else 0


# ----------------------------- Goals ---------------------------------------


def create_goal(
    distance: str,
    target_date: str | None = None,
    target_time_seconds: int | None = None,
    notes: str | None = None,
) -> int:
    """Insert a goal. Returns the new goal's id.

    ``distance`` must be one of :data:`VALID_DISTANCES`.
    ``target_date`` is an ISO date string (``YYYY-MM-DD``) or None.
    ``target_time_seconds`` is total seconds (e.g. 1500 for sub-25 min 5k) or None.
    """
    if distance not in VALID_DISTANCES:
        raise ValueError(f"distance must be one of {VALID_DISTANCES}, got {distance!r}")

    created_at = datetime.utcnow().isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO goals (distance, target_date, target_time_seconds, notes, status, created_at)
            VALUES (%s, %s, %s, %s, 'active', %s)
            RETURNING id
            """,
            (distance, target_date, target_time_seconds, notes, created_at),
        ).fetchone()
    return int(row["id"]) if row else 0


def list_goals(status: str | None = "active") -> list[dict[str, Any]]:
    """Return goals, optionally filtered by status. ``status=None`` returns all."""
    with get_connection() as conn:
        if status is None:
            rows = conn.execute(
                "SELECT * FROM goals ORDER BY created_at DESC"
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM goals WHERE status = %s ORDER BY created_at DESC",
                (status,),
            ).fetchall()
    return [dict(r) for r in rows]


def delete_goal(goal_id: int) -> bool:
    """Delete a goal by id. Returns True if a row was deleted."""
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM goals WHERE id = %s", (goal_id,))
        return cur.rowcount > 0


def set_goal_status(goal_id: int, status: str) -> bool:
    """Update a goal's status (e.g. mark as achieved)."""
    if status not in VALID_GOAL_STATUSES:
        raise ValueError(f"status must be one of {VALID_GOAL_STATUSES}")
    with get_connection() as conn:
        cur = conn.execute(
            "UPDATE goals SET status = %s WHERE id = %s", (status, goal_id)
        )
        return cur.rowcount > 0


# ----------------------------- Chat history -------------------------------


def append_chat_message(role: str, content: str) -> int:
    """Append a chat message. ``role`` must be ``'user'`` or ``'assistant'``."""
    if role not in ("user", "assistant"):
        raise ValueError("role must be 'user' or 'assistant'")
    created_at = datetime.utcnow().isoformat()
    with get_connection() as conn:
        row = conn.execute(
            "INSERT INTO chat_messages (role, content, created_at) VALUES (%s, %s, %s) RETURNING id",
            (role, content, created_at),
        ).fetchone()
    return int(row["id"]) if row else 0


def get_chat_history(limit: int = 40) -> list[dict[str, Any]]:
    """Return the most recent ``limit`` chat messages, oldest-first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM (
                SELECT * FROM chat_messages ORDER BY id DESC LIMIT %s
            ) recent ORDER BY id ASC
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in rows]


def clear_chat_history() -> int:
    """Delete all chat messages. Returns count deleted."""
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM chat_messages")
        return cur.rowcount


# ─────────────────────────── Stats / Charts ──────────────────────────────


def get_stats_summary() -> dict[str, Any]:
    """Totals for the dashboard stat cards."""
    today = date.today()
    month_start = today.replace(day=1).isoformat()
    week_start = (today - timedelta(days=today.weekday())).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                                          AS total_runs,
                COALESCE(ROUND(SUM(distance_km)::numeric, 0), 0)                  AS total_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)     AS month_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)     AS week_km
            FROM activities
            WHERE activity_type = 'running'
            """,
            (month_start, week_start),
        ).fetchone()
    return dict(row) if row else {}


def get_weekly_mileage(weeks: int = 16) -> list[dict[str, Any]]:
    """Weekly km totals for the last N weeks, oldest first."""
    cutoff = (date.today() - timedelta(weeks=weeks)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT
                TO_CHAR(DATE_TRUNC('week', start_local::date), 'YYYY-MM-DD') AS week_start,
                ROUND(SUM(distance_km)::numeric, 1)                           AS total_km,
                COUNT(*)                                                       AS run_count
            FROM activities
            WHERE start_local >= %s AND distance_km > 0
              AND activity_type = 'running'
            GROUP BY DATE_TRUNC('week', start_local::date)
            ORDER BY week_start ASC
            """,
            (cutoff,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_pace_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Last N meaningful runs (≥3 km, plausible pace) ordered oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_pace_min_per_km, distance_km
            FROM activities
            WHERE avg_pace_min_per_km IS NOT NULL
              AND avg_pace_min_per_km BETWEEN 3.0 AND 12.0
              AND distance_km >= 3
              AND activity_type = 'running'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_hr_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Last N runs (>=3 km) with a recorded avg HR, oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_hr, distance_km, avg_pace_min_per_km
            FROM activities
            WHERE avg_hr IS NOT NULL AND avg_hr > 0
              AND distance_km >= 3
              AND activity_type = 'running'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_aerobic_efficiency_runs() -> list[dict[str, Any]]:
    """Return all runs suitable for the aerobic efficiency calculation.

    Filters:
    - distance >= 3 km   (user's threshold; short runs skew the average)
    - avg_hr > 0         (must have heart rate data)
    - pace 4:00–12:00/km (excludes all-out sprints and brisk walks)
    Returns oldest first so the chart renders left → right in time.
    """
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_pace_min_per_km, avg_hr, distance_km
            FROM activities
            WHERE distance_km >= 3
              AND avg_hr > 0
              AND avg_pace_min_per_km BETWEEN 4.0 AND 12.0
              AND activity_type = 'running'
            ORDER BY start_local ASC
            """,
        ).fetchall()
    return [dict(r) for r in rows]


_PR_RANGES: dict[str, tuple[float, float]] = {
    "5k":            (4.5,  5.5),
    "10k":           (9.0, 11.0),
    "half_marathon": (19.0, 23.0),
    "marathon":      (40.0, 44.0),
}


def get_personal_records() -> dict[str, Any]:
    """Fastest run (lowest duration_min) in each standard distance bracket."""
    prs: dict[str, Any] = {}
    with get_connection() as conn:
        for label, (lo, hi) in _PR_RANGES.items():
            row = conn.execute(
                """
                SELECT start_local, distance_km, duration_min, avg_pace_min_per_km
                FROM activities
                WHERE distance_km BETWEEN %s AND %s
                  AND duration_min IS NOT NULL AND duration_min > 0
                  AND activity_type = 'running'
                ORDER BY duration_min ASC
                LIMIT 1
                """,
                (lo, hi),
            ).fetchone()
            if row:
                prs[label] = dict(row)
    return prs


# ─────────────────────────── Cycling stats ───────────────────────────────
# These mirror the running stat helpers but filter to activity_type='cycling'
# and use avg_speed_kmh (km/h) instead of pace.


def get_cycling_summary() -> dict[str, Any]:
    """Totals for the four cycling stat cards."""
    today = date.today()
    month_start = today.replace(day=1).isoformat()
    week_start = (today - timedelta(days=today.weekday())).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                                         AS total_rides,
                COALESCE(ROUND(SUM(distance_km)::numeric, 0), 0)                 AS total_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)    AS month_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)    AS week_km
            FROM activities
            WHERE activity_type = 'cycling'
            """,
            (month_start, week_start),
        ).fetchone()
    return dict(row) if row else {}


def get_cycling_weekly_distance(weeks: int = 16) -> list[dict[str, Any]]:
    """Weekly km totals for cycling, oldest first."""
    cutoff = (date.today() - timedelta(weeks=weeks)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT
                TO_CHAR(DATE_TRUNC('week', start_local::date), 'YYYY-MM-DD') AS week_start,
                ROUND(SUM(distance_km)::numeric, 1)                           AS total_km,
                COUNT(*)                                                       AS ride_count
            FROM activities
            WHERE start_local >= %s AND distance_km > 0
              AND activity_type = 'cycling'
            GROUP BY DATE_TRUNC('week', start_local::date)
            ORDER BY week_start ASC
            """,
            (cutoff,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_cycling_speed_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Recent rides (≥2 km, plausible speed) with avg speed, oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_speed_kmh, distance_km
            FROM activities
            WHERE activity_type = 'cycling'
              AND avg_speed_kmh IS NOT NULL
              AND avg_speed_kmh BETWEEN 5 AND 60
              AND distance_km >= 2
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_cycling_hr_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Recent rides (≥2 km) with a recorded avg HR, oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_hr, distance_km, avg_speed_kmh
            FROM activities
            WHERE activity_type = 'cycling'
              AND avg_hr IS NOT NULL AND avg_hr > 0
              AND distance_km >= 2
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


# ─────────────────────────── Weekly Plans ────────────────────────────────

VALID_PLAN_STATUSES = ("proposed", "accepted", "archived")


def create_weekly_plan(week_start: str, plan_json: dict[str, Any]) -> int:
    """Insert a new proposed weekly plan. Returns its id."""
    created_at = datetime.utcnow().isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO weekly_plans (week_start, plan_json, status, created_at)
            VALUES (%s, %s, 'proposed', %s)
            RETURNING id
            """,
            (week_start, Jsonb(plan_json), created_at),
        ).fetchone()
    return int(row["id"]) if row else 0


def list_weekly_plans(limit: int = 10) -> list[dict[str, Any]]:
    """Return recent non-archived plans, newest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM weekly_plans
            WHERE status != 'archived'
            ORDER BY created_at DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in rows]


def update_plan_status(plan_id: int, status: str) -> bool:
    """Change a plan's status (e.g. proposed → accepted)."""
    if status not in VALID_PLAN_STATUSES:
        raise ValueError(f"status must be one of {VALID_PLAN_STATUSES}")
    with get_connection() as conn:
        cur = conn.execute(
            "UPDATE weekly_plans SET status = %s WHERE id = %s",
            (status, plan_id),
        )
        return cur.rowcount > 0


def get_latest_weekly_plan(source: str | None = None) -> dict[str, Any] | None:
    """Return the most recent non-archived plan, optionally filtered by source.

    ``source`` matches the ``plan_json->>'source'`` field (e.g. "chat" for
    plans pasted from the AI coach). Returns None if no matching plan exists.
    """
    with get_connection() as conn:
        if source is None:
            row = conn.execute(
                """
                SELECT * FROM weekly_plans
                WHERE status != 'archived'
                ORDER BY created_at DESC
                LIMIT 1
                """,
            ).fetchone()
        else:
            row = conn.execute(
                """
                SELECT * FROM weekly_plans
                WHERE status != 'archived'
                  AND plan_json->>'source' = %s
                ORDER BY created_at DESC
                LIMIT 1
                """,
                (source,),
            ).fetchone()
    return dict(row) if row else None


# ───────────────────────────── Sleep ─────────────────────────────────────


def upsert_sleep_week(rec: dict[str, Any]) -> None:
    """Insert or update one weekly sleep summary, keyed on ``week_start``."""
    if not rec.get("week_start"):
        return
    payload = {
        "week_start":       rec.get("week_start"),
        "week_label":       rec.get("week_label"),
        "avg_score":        rec.get("avg_score"),
        "quality":          rec.get("quality"),
        "avg_duration_min": rec.get("avg_duration_min"),
        "avg_need_min":     rec.get("avg_need_min"),
        "avg_bedtime":      rec.get("avg_bedtime"),
        "avg_wake_time":    rec.get("avg_wake_time"),
        "synced_at":        datetime.utcnow().isoformat(),
    }
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO sleep_weeks
                (week_start, week_label, avg_score, quality, avg_duration_min,
                 avg_need_min, avg_bedtime, avg_wake_time, synced_at)
            VALUES
                (%(week_start)s, %(week_label)s, %(avg_score)s, %(quality)s,
                 %(avg_duration_min)s, %(avg_need_min)s, %(avg_bedtime)s,
                 %(avg_wake_time)s, %(synced_at)s)
            ON CONFLICT (week_start) DO UPDATE SET
                week_label       = excluded.week_label,
                avg_score        = COALESCE(excluded.avg_score, sleep_weeks.avg_score),
                quality          = COALESCE(excluded.quality, sleep_weeks.quality),
                avg_duration_min = COALESCE(excluded.avg_duration_min, sleep_weeks.avg_duration_min),
                avg_need_min     = COALESCE(excluded.avg_need_min, sleep_weeks.avg_need_min),
                avg_bedtime      = COALESCE(excluded.avg_bedtime, sleep_weeks.avg_bedtime),
                avg_wake_time    = COALESCE(excluded.avg_wake_time, sleep_weeks.avg_wake_time),
                synced_at        = excluded.synced_at
            """,
            payload,
        )


def count_sleep_weeks() -> int:
    """Total number of stored sleep weeks."""
    with get_connection() as conn:
        row = conn.execute("SELECT COUNT(*) AS n FROM sleep_weeks").fetchone()
    return int(row["n"]) if row else 0


def get_sleep_weeks(limit: int = 52) -> list[dict[str, Any]]:
    """Return the most recent N sleep weeks, oldest first (for charts)."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM sleep_weeks
            ORDER BY week_start DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_sleep_summary() -> dict[str, Any]:
    """Aggregate stats for the sleep stat cards (across all stored weeks)."""
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                       AS weeks_tracked,
                ROUND(AVG(avg_score)::numeric, 0)              AS avg_score,
                ROUND(AVG(avg_duration_min)::numeric, 0)       AS avg_duration_min,
                ROUND(AVG(avg_need_min)::numeric, 0)           AS avg_need_min
            FROM sleep_weeks
            """,
        ).fetchone()
    return dict(row) if row else {}


# ── Per-night sleep ──────────────────────────────────────────────────────────

_SLEEP_NIGHT_COLS = (
    "night_date", "score", "quality", "duration_min", "deep_min", "light_min",
    "rem_min", "awake_min", "stress_avg", "restless_moments", "overnight_hr",
    "resting_hr", "body_battery_change", "spo2_avg", "spo2_low",
    "respiration_avg", "respiration_low", "hrv_ms", "hrv_status",
)


def upsert_sleep_night(rec: dict[str, Any]) -> None:
    """Insert or update one night's sleep detail, keyed on ``night_date``."""
    if not rec.get("night_date"):
        return
    payload = {c: rec.get(c) for c in _SLEEP_NIGHT_COLS}
    payload["synced_at"] = datetime.utcnow().isoformat()

    cols = ", ".join(_SLEEP_NIGHT_COLS) + ", synced_at"
    placeholders = ", ".join(f"%({c})s" for c in _SLEEP_NIGHT_COLS) + ", %(synced_at)s"
    updates = ", ".join(
        f"{c} = COALESCE(excluded.{c}, sleep_nights.{c})"
        for c in _SLEEP_NIGHT_COLS if c != "night_date"
    )
    with get_connection() as conn:
        conn.execute(
            f"""
            INSERT INTO sleep_nights ({cols})
            VALUES ({placeholders})
            ON CONFLICT (night_date) DO UPDATE SET
                {updates},
                synced_at = excluded.synced_at
            """,
            payload,
        )


def count_sleep_nights() -> int:
    with get_connection() as conn:
        row = conn.execute("SELECT COUNT(*) AS n FROM sleep_nights").fetchone()
    return int(row["n"]) if row else 0


def get_sleep_nights(limit: int = 60) -> list[dict[str, Any]]:
    """Return the most recent N nights, oldest first (for charts)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM sleep_nights ORDER BY night_date DESC LIMIT %s",
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_sleep_nights_summary() -> dict[str, Any]:
    """Averages over the last 30 nights for the nightly stat cards."""
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                    AS nights_tracked,
                ROUND(AVG(score)::numeric, 0)               AS avg_score,
                ROUND(AVG(duration_min)::numeric, 0)        AS avg_duration_min,
                ROUND(AVG(deep_min)::numeric, 0)            AS avg_deep_min,
                ROUND(AVG(rem_min)::numeric, 0)             AS avg_rem_min,
                ROUND(AVG(hrv_ms)::numeric, 0)              AS avg_hrv_ms
            FROM (SELECT * FROM sleep_nights ORDER BY night_date DESC LIMIT 30) recent
            """,
        ).fetchone()
    return dict(row) if row else {}


# ───────────────────────────── Calories ──────────────────────────────────


def upsert_calories_day(rec: dict[str, Any]) -> None:
    """Insert or overwrite one day's calories, keyed on ``day_date``."""
    if not rec.get("day_date"):
        return
    payload = {
        "day_date":     rec.get("day_date"),
        "activity_cal": rec.get("activity_cal"),
        "resting_cal":  rec.get("resting_cal"),
        "total_cal":    rec.get("total_cal"),
        "synced_at":    datetime.utcnow().isoformat(),
    }
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO calories (day_date, activity_cal, resting_cal, total_cal, synced_at)
            VALUES (%(day_date)s, %(activity_cal)s, %(resting_cal)s, %(total_cal)s, %(synced_at)s)
            ON CONFLICT (day_date) DO UPDATE SET
                activity_cal = excluded.activity_cal,
                resting_cal  = excluded.resting_cal,
                total_cal    = excluded.total_cal,
                synced_at    = excluded.synced_at
            """,
            payload,
        )


def count_calories_days() -> int:
    with get_connection() as conn:
        row = conn.execute("SELECT COUNT(*) AS n FROM calories").fetchone()
    return int(row["n"]) if row else 0


def get_calorie_dates() -> list[str]:
    """All day_dates already stored, newest first (for the 'what's saved' check)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT day_date FROM calories ORDER BY day_date DESC"
        ).fetchall()
    return [r["day_date"] for r in rows]


def get_calories_days(limit: int = 60) -> list[dict[str, Any]]:
    """Return the most recent N days, oldest first (for charts)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM calories ORDER BY day_date DESC LIMIT %s",
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_calories_summary() -> dict[str, Any]:
    """Averages over the last 30 days for the calories stat cards."""
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                AS days_tracked,
                ROUND(AVG(total_cal)::numeric, 0)       AS avg_total,
                ROUND(AVG(activity_cal)::numeric, 0)    AS avg_active,
                ROUND(AVG(resting_cal)::numeric, 0)     AS avg_resting
            FROM (SELECT * FROM calories ORDER BY day_date DESC LIMIT 30) recent
            """,
        ).fetchone()
    return dict(row) if row else {}


# ───────────────────────── Nutrition (food) ──────────────────────────────


def upsert_food(
    name: str,
    kcal_per_100g: float,
    protein_per_100g: float | None = None,
    fat_per_100g: float | None = None,
    carbs_per_100g: float | None = None,
) -> None:
    """Add or overwrite a food in the personal library (keyed on lowercased name)."""
    payload = {
        "name": name.strip().lower(),
        "kcal": kcal_per_100g,
        "protein": protein_per_100g,
        "fat": fat_per_100g,
        "carbs": carbs_per_100g,
        "created_at": datetime.utcnow().isoformat(),
    }
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO foods (name, kcal_per_100g, protein_per_100g,
                               fat_per_100g, carbs_per_100g, created_at)
            VALUES (%(name)s, %(kcal)s, %(protein)s, %(fat)s, %(carbs)s, %(created_at)s)
            ON CONFLICT (name) DO UPDATE SET
                kcal_per_100g    = excluded.kcal_per_100g,
                protein_per_100g = excluded.protein_per_100g,
                fat_per_100g     = excluded.fat_per_100g,
                carbs_per_100g   = excluded.carbs_per_100g
            """,
            payload,
        )


def find_food(name: str) -> dict[str, Any] | None:
    """Look up one food by name (case-insensitive). Returns the row or None."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM foods WHERE name = %s",
            (name.strip().lower(),),
        ).fetchone()
    return dict(row) if row else None


def list_foods(limit: int = 500) -> list[dict[str, Any]]:
    """All foods in the library, alphabetically."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM foods ORDER BY name ASC LIMIT %s", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]


def count_foods() -> int:
    with get_connection() as conn:
        row = conn.execute("SELECT COUNT(*) AS n FROM foods").fetchone()
    return int(row["n"]) if row else 0


def add_food_log(
    log_date: str,
    food_name: str,
    grams: float | None,
    kcal: float | None,
    protein_g: float | None,
    fat_g: float | None,
    carbs_g: float | None,
) -> int:
    """Record one eaten item with its computed macros. Returns the new row id."""
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO food_log (log_date, food_name, grams, kcal,
                                  protein_g, fat_g, carbs_g, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (log_date, food_name, grams, kcal, protein_g, fat_g, carbs_g,
             datetime.utcnow().isoformat()),
        ).fetchone()
    return int(row["id"]) if row else 0


def get_food_log(log_date: str) -> list[dict[str, Any]]:
    """All logged items for one day, in the order they were added."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM food_log WHERE log_date = %s ORDER BY id ASC",
            (log_date,),
        ).fetchall()
    return [dict(r) for r in rows]


def delete_food_log(entry_id: int) -> bool:
    """Remove one logged item (for corrections). Returns True if a row was deleted."""
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM food_log WHERE id = %s", (entry_id,))
        return cur.rowcount > 0


def get_nutrition_day(log_date: str) -> dict[str, Any]:
    """Summed macro totals for one day."""
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                AS items,
                COALESCE(ROUND(SUM(kcal)::numeric, 0), 0)      AS kcal,
                COALESCE(ROUND(SUM(protein_g)::numeric, 1), 0) AS protein_g,
                COALESCE(ROUND(SUM(fat_g)::numeric, 1), 0)     AS fat_g,
                COALESCE(ROUND(SUM(carbs_g)::numeric, 1), 0)   AS carbs_g
            FROM food_log WHERE log_date = %s
            """,
            (log_date,),
        ).fetchone()
    return dict(row) if row else {}


def get_nutrition_days(limit: int = 30) -> list[dict[str, Any]]:
    """Recent daily macro totals, oldest first (for charts and the coach)."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT log_date,
                   ROUND(SUM(kcal)::numeric, 0)      AS kcal,
                   ROUND(SUM(protein_g)::numeric, 1) AS protein_g,
                   ROUND(SUM(fat_g)::numeric, 1)     AS fat_g,
                   ROUND(SUM(carbs_g)::numeric, 1)   AS carbs_g
            FROM food_log
            GROUP BY log_date
            ORDER BY log_date DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]
