"""PostgreSQL storage for Garmin Coach.

The app's data lives in a local Postgres database (see ``config.DATABASE_URL``).
We use raw ``psycopg`` (v3) with a small connection pool — no ORM — because the
schema is tiny and the app is single-user.

**Deduplication.** Each run is identified by its *start time truncated to the
minute* (``start_minute``, a generated column with a UNIQUE constraint). Inserts
upsert ``ON CONFLICT(start_minute)``, so re-importing the same run — whether it
arrives from a Garmin sync (real activity id) or a CSV export (synthetic id),
and regardless of small differences in the seconds field or rounding — updates
the existing row instead of creating a duplicate.

The ``raw_json`` column keeps the original payload (as JSONB) so we can extract
additional fields later without re-syncing.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta
from typing import Any, Iterable

from psycopg.rows import dict_row
from psycopg.types.json import Jsonb
from psycopg_pool import ConnectionPool

from . import config


SCHEMA = """
CREATE TABLE IF NOT EXISTS activities (
    id                  BIGINT PRIMARY KEY,
    name                TEXT,
    start_local         TEXT NOT NULL,
    -- Start time trimmed to the minute ("YYYY-MM-DD HH:MM"). This is the
    -- natural key we dedup on: the same run always has the same value here.
    start_minute        TEXT GENERATED ALWAYS AS (substr(start_local, 1, 16)) STORED UNIQUE,
    distance_km         DOUBLE PRECISION,
    duration_min        DOUBLE PRECISION,
    avg_pace_min_per_km DOUBLE PRECISION,   -- running: minutes per km
    avg_speed_kmh       DOUBLE PRECISION,   -- cycling: km per hour
    avg_hr              INTEGER,
    max_hr              INTEGER,
    vo2max              DOUBLE PRECISION,
    elevation_gain_m    DOUBLE PRECISION,
    calories            INTEGER,
    activity_type       TEXT,               -- 'running' | 'cycling'
    raw_json            JSONB,
    synced_at           TEXT NOT NULL
);

-- Add avg_speed_kmh to databases created before cycling support existed.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS avg_speed_kmh DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_activities_start_local
    ON activities (start_local);

CREATE INDEX IF NOT EXISTS idx_activities_type
    ON activities (activity_type);

CREATE TABLE IF NOT EXISTS goals (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distance            TEXT NOT NULL,        -- '5k' | '10k' | 'half_marathon' | 'marathon'
    target_date         TEXT,                  -- optional ISO date (YYYY-MM-DD)
    target_time_seconds INTEGER,               -- optional, e.g. 1500 = sub-25:00 5k
    notes               TEXT,
    status              TEXT NOT NULL DEFAULT 'active',  -- 'active' | 'achieved' | 'abandoned'
    created_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role        TEXT NOT NULL,    -- 'user' | 'assistant'
    content     TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weekly_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start  TEXT NOT NULL,
    plan_json   JSONB NOT NULL,
    status      TEXT NOT NULL DEFAULT 'proposed',  -- proposed | accepted | archived
    created_at  TEXT NOT NULL
);
"""

VALID_DISTANCES = ("5k", "10k", "half_marathon", "marathon")
VALID_GOAL_STATUSES = ("active", "achieved", "abandoned")


# --------------------------- Connection pool -------------------------------

_pool: ConnectionPool | None = None


def _get_pool() -> ConnectionPool:
    """Return the process-wide connection pool, creating it on first use.

    A pool keeps a handful of live connections open and hands them out as
    needed — far cheaper than opening a brand-new TCP+auth connection for
    every query (which is what a naive Postgres setup would do).
    """
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            conninfo=config.DATABASE_URL,
            min_size=1,
            max_size=5,
            kwargs={"row_factory": dict_row},
            open=True,
        )
        _ensure_schema(_pool)
    return _pool


def _ensure_schema(pool: ConnectionPool) -> None:
    """Create tables/indexes if they don't exist yet (idempotent)."""
    statements = [s.strip() for s in SCHEMA.split(";") if s.strip()]
    with pool.connection() as conn:
        for stmt in statements:
            conn.execute(stmt)


def get_connection():
    """Borrow a connection from the pool as a context manager.

    Usage::

        with get_connection() as conn:
            conn.execute(...)

    The connection is returned to the pool (and the transaction committed, if
    no exception was raised) when the ``with`` block exits.
    """
    return _get_pool().connection()


# ----------------------------- Activities ----------------------------------


def upsert_activity(
    summary: dict[str, Any],
    raw: dict[str, Any] | None = None,
) -> None:
    """Insert or update one activity row from a ``summarize_activity()`` dict.

    Deduplicated on ``start_minute`` (start time to the minute), so re-importing
    the same run updates the existing row rather than adding a duplicate. When a
    conflict happens we keep the *largest* id (real positive Garmin ids beat
    synthetic negative CSV ids) and use ``COALESCE`` so a sparser later import
    never wipes out data (e.g. VO2max/HR) from a richer earlier one.
    """
    if summary.get("id") is None:
        return  # can't store without a primary key

    payload = {
        "id": summary.get("id"),
        "name": summary.get("name"),
        "start_local": summary.get("start_local"),
        "distance_km": summary.get("distance_km"),
        "duration_min": summary.get("duration_min"),
        "avg_pace_min_per_km": summary.get("avg_pace_min_per_km"),
        "avg_speed_kmh": summary.get("avg_speed_kmh"),
        "avg_hr": summary.get("avg_hr"),
        "max_hr": summary.get("max_hr"),
        "vo2max": summary.get("vo2max"),
        "elevation_gain_m": summary.get("elevation_gain_m"),
        "calories": summary.get("calories"),
        "activity_type": summary.get("activity_type"),
        "raw_json": Jsonb(raw) if raw is not None else None,
        "synced_at": datetime.utcnow().isoformat(),
    }

    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO activities
                (id, name, start_local, distance_km, duration_min,
                 avg_pace_min_per_km, avg_speed_kmh, avg_hr, max_hr, vo2max,
                 elevation_gain_m, calories, activity_type, raw_json, synced_at)
            VALUES
                (%(id)s, %(name)s, %(start_local)s, %(distance_km)s, %(duration_min)s,
                 %(avg_pace_min_per_km)s, %(avg_speed_kmh)s, %(avg_hr)s, %(max_hr)s, %(vo2max)s,
                 %(elevation_gain_m)s, %(calories)s, %(activity_type)s, %(raw_json)s, %(synced_at)s)
            ON CONFLICT (start_minute) DO UPDATE SET
                id                  = GREATEST(activities.id, excluded.id),
                name                = excluded.name,
                start_local         = excluded.start_local,
                distance_km         = COALESCE(excluded.distance_km, activities.distance_km),
                duration_min        = COALESCE(excluded.duration_min, activities.duration_min),
                avg_pace_min_per_km = COALESCE(excluded.avg_pace_min_per_km, activities.avg_pace_min_per_km),
                avg_speed_kmh       = COALESCE(excluded.avg_speed_kmh, activities.avg_speed_kmh),
                avg_hr              = COALESCE(excluded.avg_hr, activities.avg_hr),
                max_hr              = COALESCE(excluded.max_hr, activities.max_hr),
                vo2max              = COALESCE(excluded.vo2max, activities.vo2max),
                elevation_gain_m    = COALESCE(excluded.elevation_gain_m, activities.elevation_gain_m),
                calories            = COALESCE(excluded.calories, activities.calories),
                activity_type       = excluded.activity_type,
                raw_json            = COALESCE(excluded.raw_json, activities.raw_json),
                synced_at           = excluded.synced_at
            """,
            payload,
        )


def upsert_many(items: Iterable[tuple[dict[str, Any], dict[str, Any]]]) -> int:
    """Bulk upsert; each item is ``(summary, raw_dict)``. Returns count inserted/updated."""
    count = 0
    for summary, raw in items:
        upsert_activity(summary, raw)
        count += 1
    return count


def get_recent_activities(days: int = 30, limit: int = 200) -> list[dict[str, Any]]:
    """Return activities from the last ``days`` days, newest first."""
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM activities
            WHERE start_local >= %s
              AND activity_type = 'running'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (cutoff, limit),
        ).fetchall()
    return [dict(r) for r in rows]


def get_activity_by_id(activity_id: int) -> dict[str, Any] | None:
    """Return a single activity row by primary key, or None if not found."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM activities WHERE id = %s",
            (activity_id,),
        ).fetchone()
    return dict(row) if row else None


def count_activities() -> int:
    """Total number of stored activities."""
    with get_connection() as conn:
        row = conn.execute("SELECT COUNT(*) AS n FROM activities").fetchone()
    return int(row["n"]) if row else 0


# ----------------------------- Goals ---------------------------------------


def create_goal(
    distance: str,
    target_date: str | None = None,
    target_time_seconds: int | None = None,
    notes: str | None = None,
) -> int:
    """Insert a goal. Returns the new goal's id.

    ``distance`` must be one of :data:`VALID_DISTANCES`.
    ``target_date`` is an ISO date string (``YYYY-MM-DD``) or None.
    ``target_time_seconds`` is total seconds (e.g. 1500 for sub-25 min 5k) or None.
    """
    if distance not in VALID_DISTANCES:
        raise ValueError(f"distance must be one of {VALID_DISTANCES}, got {distance!r}")

    created_at = datetime.utcnow().isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO goals (distance, target_date, target_time_seconds, notes, status, created_at)
            VALUES (%s, %s, %s, %s, 'active', %s)
            RETURNING id
            """,
            (distance, target_date, target_time_seconds, notes, created_at),
        ).fetchone()
    return int(row["id"]) if row else 0


def list_goals(status: str | None = "active") -> list[dict[str, Any]]:
    """Return goals, optionally filtered by status. ``status=None`` returns all."""
    with get_connection() as conn:
        if status is None:
            rows = conn.execute(
                "SELECT * FROM goals ORDER BY created_at DESC"
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM goals WHERE status = %s ORDER BY created_at DESC",
                (status,),
            ).fetchall()
    return [dict(r) for r in rows]


def delete_goal(goal_id: int) -> bool:
    """Delete a goal by id. Returns True if a row was deleted."""
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM goals WHERE id = %s", (goal_id,))
        return cur.rowcount > 0


def set_goal_status(goal_id: int, status: str) -> bool:
    """Update a goal's status (e.g. mark as achieved)."""
    if status not in VALID_GOAL_STATUSES:
        raise ValueError(f"status must be one of {VALID_GOAL_STATUSES}")
    with get_connection() as conn:
        cur = conn.execute(
            "UPDATE goals SET status = %s WHERE id = %s", (status, goal_id)
        )
        return cur.rowcount > 0


# ----------------------------- Chat history -------------------------------


def append_chat_message(role: str, content: str) -> int:
    """Append a chat message. ``role`` must be ``'user'`` or ``'assistant'``."""
    if role not in ("user", "assistant"):
        raise ValueError("role must be 'user' or 'assistant'")
    created_at = datetime.utcnow().isoformat()
    with get_connection() as conn:
        row = conn.execute(
            "INSERT INTO chat_messages (role, content, created_at) VALUES (%s, %s, %s) RETURNING id",
            (role, content, created_at),
        ).fetchone()
    return int(row["id"]) if row else 0


def get_chat_history(limit: int = 40) -> list[dict[str, Any]]:
    """Return the most recent ``limit`` chat messages, oldest-first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM (
                SELECT * FROM chat_messages ORDER BY id DESC LIMIT %s
            ) recent ORDER BY id ASC
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in rows]


def clear_chat_history() -> int:
    """Delete all chat messages. Returns count deleted."""
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM chat_messages")
        return cur.rowcount


# ─────────────────────────── Stats / Charts ──────────────────────────────


def get_stats_summary() -> dict[str, Any]:
    """Totals for the dashboard stat cards."""
    today = date.today()
    month_start = today.replace(day=1).isoformat()
    week_start = (today - timedelta(days=today.weekday())).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                                          AS total_runs,
                COALESCE(ROUND(SUM(distance_km)::numeric, 0), 0)                  AS total_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)     AS month_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)     AS week_km
            FROM activities
            WHERE activity_type = 'running'
            """,
            (month_start, week_start),
        ).fetchone()
    return dict(row) if row else {}


def get_weekly_mileage(weeks: int = 16) -> list[dict[str, Any]]:
    """Weekly km totals for the last N weeks, oldest first."""
    cutoff = (date.today() - timedelta(weeks=weeks)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT
                TO_CHAR(DATE_TRUNC('week', start_local::date), 'YYYY-MM-DD') AS week_start,
                ROUND(SUM(distance_km)::numeric, 1)                           AS total_km,
                COUNT(*)                                                       AS run_count
            FROM activities
            WHERE start_local >= %s AND distance_km > 0
              AND activity_type = 'running'
            GROUP BY DATE_TRUNC('week', start_local::date)
            ORDER BY week_start ASC
            """,
            (cutoff,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_pace_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Last N meaningful runs (≥3 km, plausible pace) ordered oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_pace_min_per_km, distance_km
            FROM activities
            WHERE avg_pace_min_per_km IS NOT NULL
              AND avg_pace_min_per_km BETWEEN 3.0 AND 12.0
              AND distance_km >= 3
              AND activity_type = 'running'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_hr_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Last N runs (>=3 km) with a recorded avg HR, oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_hr, distance_km, avg_pace_min_per_km
            FROM activities
            WHERE avg_hr IS NOT NULL AND avg_hr > 0
              AND distance_km >= 3
              AND activity_type = 'running'
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_aerobic_efficiency_runs() -> list[dict[str, Any]]:
    """Return all runs suitable for the aerobic efficiency calculation.

    Filters:
    - distance >= 3 km   (user's threshold; short runs skew the average)
    - avg_hr > 0         (must have heart rate data)
    - pace 4:00–12:00/km (excludes all-out sprints and brisk walks)
    Returns oldest first so the chart renders left → right in time.
    """
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_pace_min_per_km, avg_hr, distance_km
            FROM activities
            WHERE distance_km >= 3
              AND avg_hr > 0
              AND avg_pace_min_per_km BETWEEN 4.0 AND 12.0
              AND activity_type = 'running'
            ORDER BY start_local ASC
            """,
        ).fetchall()
    return [dict(r) for r in rows]


_PR_RANGES: dict[str, tuple[float, float]] = {
    "5k":            (4.5,  5.5),
    "10k":           (9.0, 11.0),
    "half_marathon": (19.0, 23.0),
    "marathon":      (40.0, 44.0),
}


def get_personal_records() -> dict[str, Any]:
    """Fastest run (lowest duration_min) in each standard distance bracket."""
    prs: dict[str, Any] = {}
    with get_connection() as conn:
        for label, (lo, hi) in _PR_RANGES.items():
            row = conn.execute(
                """
                SELECT start_local, distance_km, duration_min, avg_pace_min_per_km
                FROM activities
                WHERE distance_km BETWEEN %s AND %s
                  AND duration_min IS NOT NULL AND duration_min > 0
                  AND activity_type = 'running'
                ORDER BY duration_min ASC
                LIMIT 1
                """,
                (lo, hi),
            ).fetchone()
            if row:
                prs[label] = dict(row)
    return prs


# ─────────────────────────── Cycling stats ───────────────────────────────
# These mirror the running stat helpers but filter to activity_type='cycling'
# and use avg_speed_kmh (km/h) instead of pace.


def get_cycling_summary() -> dict[str, Any]:
    """Totals for the four cycling stat cards."""
    today = date.today()
    month_start = today.replace(day=1).isoformat()
    week_start = (today - timedelta(days=today.weekday())).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                                         AS total_rides,
                COALESCE(ROUND(SUM(distance_km)::numeric, 0), 0)                 AS total_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)    AS month_km,
                COALESCE(ROUND(SUM(CASE WHEN start_local >= %s
                                THEN distance_km ELSE 0 END)::numeric, 1), 0)    AS week_km
            FROM activities
            WHERE activity_type = 'cycling'
            """,
            (month_start, week_start),
        ).fetchone()
    return dict(row) if row else {}


def get_cycling_weekly_distance(weeks: int = 16) -> list[dict[str, Any]]:
    """Weekly km totals for cycling, oldest first."""
    cutoff = (date.today() - timedelta(weeks=weeks)).isoformat()
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT
                TO_CHAR(DATE_TRUNC('week', start_local::date), 'YYYY-MM-DD') AS week_start,
                ROUND(SUM(distance_km)::numeric, 1)                           AS total_km,
                COUNT(*)                                                       AS ride_count
            FROM activities
            WHERE start_local >= %s AND distance_km > 0
              AND activity_type = 'cycling'
            GROUP BY DATE_TRUNC('week', start_local::date)
            ORDER BY week_start ASC
            """,
            (cutoff,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_cycling_speed_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Recent rides (≥2 km, plausible speed) with avg speed, oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_speed_kmh, distance_km
            FROM activities
            WHERE activity_type = 'cycling'
              AND avg_speed_kmh IS NOT NULL
              AND avg_speed_kmh BETWEEN 5 AND 60
              AND distance_km >= 2
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


def get_cycling_hr_trend(limit: int = 30) -> list[dict[str, Any]]:
    """Recent rides (≥2 km) with a recorded avg HR, oldest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT start_local, avg_hr, distance_km, avg_speed_kmh
            FROM activities
            WHERE activity_type = 'cycling'
              AND avg_hr IS NOT NULL AND avg_hr > 0
              AND distance_km >= 2
            ORDER BY start_local DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


# ─────────────────────────── Weekly Plans ────────────────────────────────

VALID_PLAN_STATUSES = ("proposed", "accepted", "archived")


def create_weekly_plan(week_start: str, plan_json: dict[str, Any]) -> int:
    """Insert a new proposed weekly plan. Returns its id."""
    created_at = datetime.utcnow().isoformat()
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO weekly_plans (week_start, plan_json, status, created_at)
            VALUES (%s, %s, 'proposed', %s)
            RETURNING id
            """,
            (week_start, Jsonb(plan_json), created_at),
        ).fetchone()
    return int(row["id"]) if row else 0


def list_weekly_plans(limit: int = 10) -> list[dict[str, Any]]:
    """Return recent non-archived plans, newest first."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT * FROM weekly_plans
            WHERE status != 'archived'
            ORDER BY created_at DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in rows]


def update_plan_status(plan_id: int, status: str) -> bool:
    """Change a plan's status (e.g. proposed → accepted)."""
    if status not in VALID_PLAN_STATUSES:
        raise ValueError(f"status must be one of {VALID_PLAN_STATUSES}")
    with get_connection() as conn:
        cur = conn.execute(
            "UPDATE weekly_plans SET status = %s WHERE id = %s",
            (status, plan_id),
        )
        return cur.rowcount > 0


def get_latest_weekly_plan(source: str | None = None) -> dict[str, Any] | None:
    """Return the most recent non-archived plan, optionally filtered by source.

    ``source`` matches the ``plan_json->>'source'`` field (e.g. "chat" for
    plans pasted from the AI coach). Returns None if no matching plan exists.
    """
    with get_connection() as conn:
        if source is None:
            row = conn.execute(
                """
                SELECT * FROM weekly_plans
                WHERE status != 'archived'
                ORDER BY created_at DESC
                LIMIT 1
                """,
            ).fetchone()
        else:
            row = conn.execute(
                """
                SELECT * FROM weekly_plans
                WHERE status != 'archived'
                  AND plan_json->>'source' = %s
                ORDER BY created_at DESC
                LIMIT 1
                """,
                (source,),
            ).fetchone()
    return dict(row) if row else None
